### PR TITLE
readme: document extensions

### PR DESCRIPTION
**Pull request by glensc**
this project lacked description, what does the package contains.

tried to deduct the information from:
- https://raw.githubusercontent.com/jgm/commonmark.js/0.24.0/test/smart_punct.txt
- https://commonmark.thephpleague.com/customization/inline-parsing/#example-1---twitter-handles

they both seemed to be added in 0.1.0 with no docs:
- https://github.com/thephpleague/commonmark-extras/blob/9a3254bec56396e1f9c58911bdee2b38669b7a56/CHANGELOG.md#010---2016-01-13

### CODE REVIEW

**Comment by glensc** [comment]
@colinodell uh, looks like there's duplicate extension

https://github.com/thephpleague/commonmark/tree/94305093262b9448b1aa8d40eb1178c2ad0508a5#league-extensions:

> [league/commonmark-ext-smartpunct](https://github.com/thephpleague/commonmark-ext-smartpunct) ( 2 hours ago) - Intelligently converts ASCII quotes, dashes, and ellipses to their Unicode equivalents

**Comment by colinodell** [comment]
Yep I just created that today. My goal is to pull out the individual extensions and then deprecate this one.

**Comment by glensc** [comment]
what about strikethrough then? https://github.com/thephpleague/commonmark-extras/pull/18

I attempted to finish the previous PR.

**Comment by colinodell** [comment]
We can merge that once completed, pull that into a separate repo, and then decide what do with this one.

Right now I'm thinking we'll either deprecate / "abandon" this package or turn it into a meta-package which pulls in the things we've split off.  I'm currently leaning towards that second option.

**Pull request merged**
