### PR TITLE
Allow use with commonmark 0.15

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by colinodell** [comment]
Thanks Graham!

**Comment by GrahamCampbell** [comment]
:)

**Comment by GrahamCampbell** [comment]
Any chance we could get a v0.2.0 tag please?

**Comment by colinodell** [comment]
I think we can do 0.1.2 since no code changes were made since 0.1.1 - just compatibility with dependency versions :)

**Comment by colinodell** [comment]
@GrahamCampbell: https://github.com/thephpleague/commonmark-extras/releases/tag/0.1.2  Thanks as always!

**Pull request merged**
