### PR TITLE
Add Strike Through support extension

### PR DESCRIPTION
**Pull request by glensc**
Replaces: #13

### CODE REVIEW

**Comment by glensc** [comment]
hmm, the `uafrica/commonmark-ext` project doesn't contain anything else than the `StrikeThroughExtension`, should this project composer somehow indicate that?

And the code is very similar, some differences about `Xml::escape`.
I do not know which project is right, there's no info how @tankerkiller125 created the previous PR.

maybe they both copied it from commonmark docs and just evolved to something different.

**Comment by glensc** [comment]
looked at the `uafrica` pull requests. the xml encode was added here: https://github.com/uafrica/commonmark-ext/pull/2/files

and a bit funny, some of his code was added to make tests to work... meh!?

@colinodell you can perhaps indicate what's up with that?

**Comment by glensc** [comment]
@colinodell please review this next

as for new project split:
- https://github.com/thephpleague/commonmark-extras/pull/15#issuecomment-472012806

I prefer not to squash commits to single commit, but preserve their history.

The commits affect only files related to single extension, should be possible to cherry-pick and rebase them. I could attempt to do that.

Created empty repo, and I'll try to add commits there to branch: https://github.com/glensc/commonmark-ext-striketrough

**Comment by glensc** [comment]
or, https://github.com/uafrica/commonmark-ext could be perhaps transferred and renamed to this organization?

**Comment by colinodell** [comment]
@dakota @johanmeiring would you have any interest in bringing your `uafrica/commonmark-ext` strikethrough extension into the PHP League as a semi-official extension named `league/commonmark-ext-strikethrough`?  Right now we're considering whether we want to accept this alternative strikethrough implementation, but I know you have your own extension which offers similar functionality, so I'd like to offer the opportunity to use your extension as the base and grant you full contributor access to continue maintenance.

To be completely candid, here's what I'm proposing:

1. We'd fork your repository into the PHP League and add you as contributors to that fork
2. I would handle the process of updating the namespaces
3. Myself and other community members will add additional tests and adjust the code to work with the upcoming 0.19 release of `league/commonmark`
4. We'll release the new package
5. Once released, you would mark your project as "abandoned" in Packagist, recommending the new fork as the preferred version
6. We would continue maintaining the fork as co-equal contributors

**Please do not feel pressured into saying yes!**  I'm simply offering the opportunity in case you are interested and would like additional help maintaining the extension.  I will not be offended if you say "no" for any reason.  Just let me know!

**Comment by johanmeiring** [comment]
@colinodell Thanks for reaching out.  We've scheduled a meeting to discuss this at uAfrica tomorrow morning and will give you an answer shortly thereafter 👍

**Comment by johanmeiring** [comment]
@colinodell You're welcome to proceed.  We're happy to have the League take ownership of this extension, and welcome the opportunity to work with you on maintaining it.  Please let us know if there's any preparation work we need to do on our side, and also when we can mark the existing package as abandoned.

**Comment by colinodell** [comment]
Awesome, thank you @johanmeiring!  I will get working on this right away.

The only thing I need from you right now is how you'd like to handle the copyright.  We can keep it licensed under MIT.  But are you okay if we update the copyright notice to be:

```
Copyright (c) 2019, Colin O'Dell & uAfrica.com (http://uafrica.com)
```

Let me know your thoughts!

**Comment by johanmeiring** [comment]
@colinodell Our technical director is happy with your proposed change in the copyright notice, you may proceed :-)

**Comment by colinodell** [comment]
Sorry for the delay @johanmeiring.  I have forked the project and updated everything accordingly: https://github.com/thephpleague/commonmark-ext-strikethrough  I also added you to the project as a contributor for any maintenance you'd like to assist with :)

The final step would be to mark your package as `abandoned` in favor of `league/commonmark-ext-strikethrough` via Packagist: https://packagist.org/packages/uafrica/commonmark-ext/abandon  Once done, Packagist and Composer will recommend that people use the newer package instead.  (They aren't forced to though - they can keep using the original one without any issues should they choose)

Feel free to reach out if you have any questions. I look forward to working with you on this!

**Comment by colinodell** [comment]
@glensc I appreciate your PR but I'm going to close it now that we have an official extension per your suggestion in https://github.com/thephpleague/commonmark-extras/pull/18#issuecomment-472416617!  Thanks so much!

**Comment by johanmeiring** [comment]
@colinodell Cool stuff, thanks for your efforts.  I'll ask the person responsible for our Packagist account to make the necessary changes early next week.

**Comment by jacoroux** [comment]
@colinodell @johanmeiring I have now marked the package (https://packagist.org/packages/uafrica/commonmark-ext) as abandoned.

**Comment by glensc** [comment]
> This package is abandoned and no longer maintained. No replacement package was suggested.

You should suggest the new package name as the replacement.

**Comment by johanmeiring** [comment]
@glensc Problem solved, apologies for the inconvenience 👍

**Pull request closed without merging**
