### PR TITLE
Strike through support extension

### PR DESCRIPTION
**Pull request by tankerkiller125**
Adds strike through support, still needs a functional test (couldn't get test to work saying their was no parser for the Document type)

### CODE REVIEW

**Comment by markcarver** [comment]
This would be awesome

**Comment by markcarver** [comment]
Especially considering that https://github.com/uafrica/commonmark-ext is severely outdated and doesn't seem to be well maintained.

**Comment by markcarver** [comment]
FWIW, you could probably just port some of the existing https://github.com/uafrica/commonmark-ext tests into this PR. I would, but I don't want to duplicate the effort with this PR.

**Comment by colinodell** [comment]
I haven't looked closely at that package or its tests, but if they seem comprehensive enough then I like  @markcarver's suggestion of porting them.

**Comment by colinodell** [comment]
FYI having some solid tests is the only thing preventing me from merging this right now :wink:

**Comment by tankerkiller125** [comment]
@colinodell sounds good, let me see what I can do in the next couple of days

**Comment by glensc** [comment]
@tankerkiller125 would you be able to finish this?

**Comment by tankerkiller125** [comment]
@glensc Unfortunately I don't think i currently have the time to complete the test so that this can be merged.

**Comment by glensc** [comment]
@tankerkiller125 no problem, I can try porting these myself:
- https://github.com/thephpleague/commonmark-extras/pull/13#issuecomment-377495197

just did not want to do duplicate work and also did not want you to be left out if I just took over without asking first.

**Comment by glensc** [comment]
added commits top of this branch:
- https://github.com/thephpleague/commonmark-extras/pull/18

you can close this PR.

**Pull request closed without merging**
